version: 2

updates:
  # Root (workspace)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]

  # Core package
  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "daily"
    target-branch: "develop"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(core)"

  # VSCode extension
  - package-ecosystem: "npm"
    directory: "/packages/vscode-ext"
    schedule:
      interval: "daily"
    target-branch: "develop"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(ext)"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
